name: Deploy WebSocket App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up SSH for DigitalOcean
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

    # - name: Add DigitalOcean server to known_hosts
    #   run: ssh-keyscan -H ${{ secrets.DO_SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Clean up old files on DigitalOcean
      run: |
          rm -rf /root/app/*

    - name: Copy WebSocket App files to DigitalOcean
      run: |
        scp -r ./client/main.go ./server/room.go root@${{ secrets.DO_SERVER_IP }}:/root/app/

    - name: Connect to DigitalOcean and deploy the app
      run: |
        ssh root@${{ secrets.DO_SERVER_IP }} << 'EOF'
          cd /root/app/
          echo "Building and running the WebSocket server..."
          
          # Install Go if it's not installed
          if ! [ -x "$(command -v go)" ]; then
            echo "Installing Go..."
            wget https://golang.org/dl/go1.19.7.linux-amd64.tar.gz
            tar -xvf go1.19.7.linux-amd64.tar.gz
            mv go /usr/local
            export GOROOT=/usr/local/go
            export GOPATH=$HOME/go
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
          fi

          # Build the WebSocket app
          go mod init websocket-app || true
          go mod tidy
          go build -o websocket-server main.go room.go

          # Stop any running instances of the app
          pkill -f websocket-server || true

          # Run the WebSocket server in the background
          nohup ./websocket-server &

          echo "WebSocket server is running on port 8080"
        EOF
